### ISSUE TITLE
KDUMP_ATTR_ARCH_NAME not set in v5.11 Linux Kernel Dump

### ISSUE THREAD

**Issue by sdimitro** [ptesarik/libkdumpfile#36]
## Baseline - Before:

Generating a crash dump on a system running Ubuntu with a v5.4 kernel and using [drgn](https://github.com/delphix/drgn) (which in turn uses libkdumpfile to read the crash dump) worked as expected. The crash dump itself was read correctly and kdumpfile's context for it has its `arch.name` attribute (aka `KDUMP_ATTR_ARCH_NAME` populated correctly.

```
user@hostname:/var/crash/202111161828$ sudo dumpattr dump.202111161828 arch
arch:
  page_shift: 12
  page_size: 4096
  ptr_size: 8
  byte_order: 1
  name: x86_64       // <------- HERE
  pteval_size: 8

user@hostname:/var/crash/202111161828$ sudo dumpattr dump.202111161828 arch.name
arch.name: x86_64
```

## Unexpected Behavior - Now:

Generating a crash dump on a system running Ubuntu with a v5.11 and using drgn on it fails with the following error message from the respective libkdumpfile call and message:
```
Exception: kdump_get_string_attr(KDUMP_ATTR_ARCH_NAME): Key has no value
```

Looking at the dumps attributes we see that `arch.name` is missing:
```
user@hostname:/var/crash/202111101006$ sudo dumpattr dump.202111162023 arch
arch:
  page_shift: 12
  page_size: 4096
  ptr_size: 8
  byte_order: 1

user@hostname:/var/crash/202111101006$ sudo dumpattr dump.202111162023 arch.name
kdump_attr_ref_get failed: Key has no value
arch.name:
```

The reason I believe that this is a libkdumpfile bug is because in the v5.11 dump I can see that the architecture name is part of the crash dump at the exact same place that it used to be for the v5.4:
```
user@hostname:/var/crash/202111101006$ sudo strings dump.202111162023 | head -n 10
KDUMP
hostname
5.11.0-1021-aws
#22~20.04.2 SMP Thu Nov 11 05:32:46 UTC 2021
x86_64
(none)
CORE
CORE
VMCOREINFO
OSRELEASE=5.11.0-1021-aws
```

I'd appreciate any help with this!

**Comment by sdimitro** [comment]
After trying to use `crash-util` on the v5.11 crash dump I'm even more convinced that there is some parsing issue that we need to catch up with because crash v7.2.8 fails to parse the dump:
```
$ sudo crash /usr/lib/debug/boot/vmlinux-5.11.0-1021-aws dump.202111162023

crash 7.2.8
Copyright (C) 2002-2020  Red Hat, Inc.
Copyright (C) 2004, 2005, 2006, 2010  IBM Corporation
Copyright (C) 1999-2006  Hewlett-Packard Co
Copyright (C) 2005, 2006, 2011, 2012  Fujitsu Limited
Copyright (C) 2006, 2007  VA Linux Systems Japan K.K.
Copyright (C) 2005, 2011  NEC Corporation
Copyright (C) 1999, 2002, 2007  Silicon Graphics, Inc.
Copyright (C) 1999, 2000, 2001, 2002  Mission Critical Linux, Inc.
This program is free software, covered by the GNU General Public License,
and you are welcome to change it and/or distribute copies of it under
certain conditions.  Enter "help copying" to see the conditions.
This program has absolutely no warranty.  Enter "help warranty" for details.

crash: dump.202111162023: not a supported file format
```

But the newer version from master (7.3.0++) doesn't:
```
$ sudo crash /usr/lib/debug/boot/vmlinux-5.11.0-1021-dx2021111105-4e77a59b5-aws dump.202111162023

crash 7.3.0++
Copyright (C) 2002-2021  Red Hat, Inc.
Copyright (C) 2004, 2005, 2006, 2010  IBM Corporation
Copyright (C) 1999-2006  Hewlett-Packard Co
Copyright (C) 2005, 2006, 2011, 2012  Fujitsu Limited
Copyright (C) 2006, 2007  VA Linux Systems Japan K.K.
Copyright (C) 2005, 2011, 2020-2021  NEC Corporation
Copyright (C) 1999, 2002, 2007  Silicon Graphics, Inc.
Copyright (C) 1999, 2000, 2001, 2002  Mission Critical Linux, Inc.
Copyright (C) 2015, 2021  VMware, Inc.
This program is free software, covered by the GNU General Public License,
and you are welcome to change it and/or distribute copies of it under
certain conditions.  Enter "help copying" to see the conditions.
This program has absolutely no warranty.  Enter "help warranty" for details.

GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...

      KERNEL: /usr/lib/debug/boot/vmlinux-5.11.0-1021-aws
    DUMPFILE: dump.202111162023  [PARTIAL DUMP]
        CPUS: 2
        DATE: Tue Nov 16 20:23:16 UTC 2021
      UPTIME: 01:29:00
LOAD AVERAGE: 0.02, 0.09, 0.12
       TASKS: 905
    NODENAME: ip-10-110-235-14
     RELEASE: 5.11.0-1021-aws
     VERSION: #22~20.04.2 SMP Thu Nov 11 05:32:46 UTC 2021
     MACHINE: x86_64  (2499 Mhz)
      MEMORY: 7.9 GB
       PANIC: "Kernel panic - not syncing: sysrq triggered crash"
         PID: 17522
     COMMAND: "bash"
        TASK: ffff96b174350000  [THREAD_INFO: ffff96b174350000]
         CPU: 0
       STATE: TASK_RUNNING (PANIC)

crash>
```

**Comment by ptesarik** [comment]
Thanks for checking the situation with `crash`. I wonder why this bug hasn't been found by SUSE QA yet, because SLE15 SP4 has upgraded the kernel to 5.14, so it is most likely also affected, but maybe the bug report just hasn't reached me yet.

Working on it!

**Comment by ptesarik** [comment]
I can confirm that SLE15 SP4 Alpha-202111-1 internal snapshot (kernel version 5.14) is also affected. It should be easy for me to continue from here.

**Comment by ptesarik** [comment]
After some research, I'm not sure I'm seeing the same issue. For me, the KDUMP file is not properly formatted (suggesting a bug in `makedumpfile`).

@sdimitro Can you share the first 8 kilobytes of your KDUMP file with me, please?

**Comment by ptesarik** [comment]
FWIW after upgrading to makedumpfile-1.6.9, I am no longer able to reproduce the issue:

```
ptesarik@armageddon:~> dumpattr sle15-sp4/vmcore-new-makedumpfile arch
arch: 
  page_shift: 12
  page_size: 4096
  ptr_size: 8
  byte_order: 1
  name: x86_64
  pteval_size: 8
```

**Comment by ptesarik** [comment]
> The reason I believe that this is a libkdumpfile bug is because in the v5.11 dump I can see that the architecture name is part of the crash dump at the exact same place that it used to be for the v5.4:
> 
> ```
> user@hostname:/var/crash/202111101006$ sudo strings dump.202111162023 | head -n 10
> KDUMP
> hostname
> 5.11.0-1021-aws
> #22~20.04.2 SMP Thu Nov 11 05:32:46 UTC 2021
> x86_64
> (none)
> CORE
> CORE
> VMCOREINFO
> OSRELEASE=5.11.0-1021-aws
> ```

Hmm, since the complete utsname is copied to the KDUMP header, I would have expected `Linux` as _sysname_ between `KDUMP` and `hostname`. But with an incompatible `makedumpfile`, the address is off by 4 bytes, chopping off the initial `Linu` from _sysname_ like here:

```
tesarik@ezekiel:~> xxd -l 128 vmcore-bad
00000000: 4b44 554d 5020 2020 0600 0000 7800 0000  KDUMP   ....x...
00000010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 006c 6f63 616c 686f  .........localho
00000050: 7374 0000 0000 0000 0000 0000 0000 0000  st..............
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

Compare it to a dump taken with makedumpfile-1.6.9:
```
ptesarik@armageddon:~> xxd -l 128 vmcore-new-makedumpfile 
00000000: 4b44 554d 5020 2020 0600 0000 4c69 6e75  KDUMP   ....Linu
00000010: 7800 0000 0000 0000 0000 0000 0000 0000  x...............
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 006c 6f63  .............loc
00000050: 616c 686f 7374 0000 0000 0000 0000 0000  alhost..........
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

The `crash` utility can deal with such broken dump files, because it supports only one target architecture. But you can see the wrong data with `crash` command `help -D`:

```
            header: 559106b685f0
           signature: "KDUMP   "
      header_version: 6
             utsname:
               sysname: x
              nodename: lhost
               release: .15-1-default
               version: MP Wed Oct 27 10:51:24 UTC 2021 (5106ba8)
               machine: 64
```

I wonder if your dump files look similar.

**Comment by sdimitro** [comment]
You are definitely right!

Looking at my crash dump with `crash` and running `help -D` I see the exact same issue:
```
           header: 556b6fc76dc0
           signature: "KDUMP   "
      header_version: 6
             utsname:
               sysname: x
              nodename: 0-110-235-14
               release: .0-1021-aws
               version: 20.04.2 SMP Thu Nov 11 05:32:46 UTC 2021
               machine: 64
```

@ptesarik do you by any chance have the commit in the `makedumpfile` repo that introduced the issue or the one that fixed it?

No worries if not, just let me know and I'll close the issue. I appreciate you helping me with this issue and I hope that find is helpful to your organization too.
